name: total-var
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - colorama=0.4.4
  - cycler=0.10.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=12.0.1
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - llvm-openmp=12.0.1
  - lz4-c=1.9.2
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - munkres=1.1.4
  - ncurses=6.2
  - numpy=1.21.1
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=7.2.0
  - pip=21.2.2
  - pyparsing=2.4.7
  - python=3.8.11
  - python-dateutil=2.8.2
  - python_abi=3.8
  - readline=8.1
  - scipy=1.7.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.62.0
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
